pipeline{
    agent any
    environment {
        PATH = "$PATH:/opt/apache-maven-3.8.2/bin"
    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/narsaiah83/JavaWebCalculator.git'
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
    }
        stage('SonarQube analysis') {
//    def scannerHome = tool 'SonarScanner 4.0';
        steps{
        withSonarQubeEnv('sonarserver') { 
        // If you have configured more than one global server connection, you can specify its name
//      sh "${scannerHome}/bin/sonar-scanner"
        sh "mvn sonar:sonar"
    }
        }
        }
}
    stage('Deploy Artifacts to Nexus') {
        nexusArtifactUploader artifacts 
            
        artifactId: 'springboot', 
        classifier: '',
        file: 'maven-central-repo/Uber.jar',
        type: 'jar']], 
        credentialsId: 'admin123',
        groupId: 'com.example', 
        nexusUrl: '54.234.166.21:8081/', 
        nexusVersion: 'nexus2', 
        protocol: 'http', 
        repository: 'mvn-repo', 
        version: '1.0.0'
            }
        }
   }
